
---
events:
  -
    kind: "message-v1"
    backtrace:
      - "D:/Cmake/share/cmake-3.26/Modules/CMakeDetermineSystem.cmake:199 (message)"
      - "CMakeLists.txt:17 (project)"
    message: |
      The target system is: Generic - 1 - 
      The host system is: Windows - 10.0.22631 - AMD64
...
